spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}

  sql:
    init:
      mode: never

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
        jdbc:
          time_zone: UTC
    defer-datasource-initialization: false

hirecore:
  cors:
    allowed-origins: ${DEV_CORS_ALLOWED_ORIGINS}
    allowed-methods:
      - "GET"
      - "POST"
      - "PUT"
      - "PATCH"
      - "DELETE"
      - "OPTIONS"
    allowed-headers:
      - "*"
    allow-credentials: true

  cookie:
    http-only: true
    secure: false
    same-site: Lax

  jwt:
    secret: ${DEV_JWT_SECRET}
    access-expiration-millis: 10800000
    refresh-expiration-millis: 604800000

  oauth2:
    kakao:
      client-redirect-url: ${DEV_KAKAO_CLIENT_REDIRECT_URL}
      client-id: ${DEV_KAKAO_CLIENT_ID}
      client-secret: ${DEV_KAKAO_CLIENT_SECRET}
      grant-type: authorization_code
      token-issue-url: https://kauth.kakao.com/oauth/token
      user-profile-url: https://kapi.kakao.com/v2/user/me

  object-storage:
    aws:
      region: ${DEV_OBJECT_STORAGE_AWS_REGION}
      s3:
        bucket: ${DEV_OBJECT_STORAGE_AWS_S3_BUCKET}
        path-style-access: false
      cloud-front:
        public-base-url: ${DEV_OBJECT_STORAGE_AWS_CF_PUBLIC_BASE_URL}
