----------------------
-- user_membership_policies
----------------------
INSERT IGNORE INTO user_membership_policies (
       id, code, name, content, amount,
       storage_quota_byte, active,
       created_at, updated_at
) VALUES (1, 'TEST_CODE', '골드 멤버십', '골드 멤버십 정책', 10000, 41943040, true, NOW(), NOW());

----------------------
-- job_category
----------------------
-- =========================================================
-- job_category seed
-- 기준 컬럼:
-- (id, parent_id, category_code, category_name, depth,
--  is_active, is_assignable, allows_custom_input,
--  sort_order, created_at, updated_at)
-- =========================================================

-- =========================================================
-- LEVEL 1
-- =========================================================
INSERT IGNORE INTO job_category (
    id, parent_id, category_code, category_name, depth,
    is_active, is_assignable, allows_custom_input,
    sort_order, created_at, updated_at
) VALUES
    (10000, NULL, 'DEVELOPMENT_DATA', '개발·데이터', 1, TRUE, FALSE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (20000, NULL, 'PLANNING_STRATEGY', '기획·전략', 1, TRUE, FALSE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (30000, NULL, 'DESIGN', '디자인', 1, TRUE, FALSE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (40000, NULL, 'MARKETING_AD', '마케팅·광고', 1, TRUE, FALSE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (50000, NULL, 'BUSINESS_MANAGEMENT', '경영·비즈니스', 1, TRUE, FALSE, FALSE, 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (60000, NULL, 'SALES_SERVICE', '영업·서비스', 1, TRUE, FALSE, FALSE, 60, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (70000, NULL, 'MEDIA_CONTENT', '미디어·콘텐츠', 1, TRUE, FALSE, FALSE, 70, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (80000, NULL, 'EDUCATION', '교육', 1, TRUE, FALSE, FALSE, 80, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- =========================================================
-- 개발·데이터
-- =========================================================
INSERT IGNORE INTO job_category (
    id, parent_id, category_code, category_name, depth,
    is_active, is_assignable, allows_custom_input,
    sort_order, created_at, updated_at
) VALUES
    (11000, 10000, 'SOFTWARE_ENGINEERING', 'SW개발', 2, TRUE, FALSE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (12000, 10000, 'DATA_AI', '데이터·AI', 2, TRUE, FALSE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (13000, 10000, 'INFRA_PLATFORM', '인프라·플랫폼', 2, TRUE, FALSE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (14000, 10000, 'SECURITY_QUALITY', '보안·품질', 2, TRUE, FALSE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT IGNORE INTO job_category (
    id, parent_id, category_code, category_name, depth,
    is_active, is_assignable, allows_custom_input,
    sort_order, created_at, updated_at
) VALUES
    (11100, 11000, 'BACKEND_ENGINEER', '백엔드 개발', 3, TRUE, TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (11200, 11000, 'FRONTEND_ENGINEER', '프론트엔드 개발', 3, TRUE, TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (11300, 11000, 'FULLSTACK_ENGINEER', '풀스택 개발', 3, TRUE, TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (11400, 11000, 'MOBILE_APP_ENGINEER', '모바일 앱 개발', 3, TRUE, TRUE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (11500, 11000, 'GAME_CLIENT_ENGINEER', '게임 클라이언트 개발', 3, TRUE, TRUE, FALSE, 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (11600, 11000, 'GAME_SERVER_ENGINEER', '게임 서버 개발', 3, TRUE, TRUE, FALSE, 60, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (11700, 11000, 'EMBEDDED_IOT_ENGINEER', '임베디드·IoT 개발', 3, TRUE, TRUE, FALSE, 70, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (11800, 11000, 'SOFTWARE_ENGINEERING_OTHER', '기타(직접입력)', 3, TRUE, TRUE, TRUE, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (12100, 12000, 'DATA_ANALYST', '데이터 분석', 3, TRUE, TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (12200, 12000, 'DATA_ENGINEER', '데이터 엔지니어', 3, TRUE, TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (12300, 12000, 'DATA_SCIENTIST', '데이터 사이언티스트', 3, TRUE, TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (12400, 12000, 'MACHINE_LEARNING_ENGINEER', '머신러닝 엔지니어', 3, TRUE, TRUE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (12500, 12000, 'AI_APPLICATION_ENGINEER', 'AI 애플리케이션 개발', 3, TRUE, TRUE, FALSE, 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (12600, 12000, 'MLOPS_ENGINEER', 'MLOps 엔지니어', 3, TRUE, TRUE, FALSE, 60, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (12700, 12000, 'DATA_AI_OTHER', '기타(직접입력)', 3, TRUE, TRUE, TRUE, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (13100, 13000, 'DEVOPS_ENGINEER', 'DevOps 엔지니어', 3, TRUE, TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (13200, 13000, 'CLOUD_ENGINEER', '클라우드 엔지니어', 3, TRUE, TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (13300, 13000, 'SRE', 'SRE', 3, TRUE, TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (13400, 13000, 'SYSTEM_ENGINEER', '시스템 엔지니어', 3, TRUE, TRUE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (13500, 13000, 'NETWORK_ENGINEER', '네트워크 엔지니어', 3, TRUE, TRUE, FALSE, 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (13600, 13000, 'DBA', 'DBA', 3, TRUE, TRUE, FALSE, 60, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (13700, 13000, 'INFRA_PLATFORM_OTHER', '기타(직접입력)', 3, TRUE, TRUE, TRUE, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (14100, 14000, 'SECURITY_ENGINEER', '보안 엔지니어', 3, TRUE, TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (14200, 14000, 'QA_ENGINEER', 'QA 엔지니어', 3, TRUE, TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (14300, 14000, 'TEST_AUTOMATION_ENGINEER', '테스트 자동화', 3, TRUE, TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (14400, 14000, 'PERFORMANCE_TEST_ENGINEER', '성능 테스트', 3, TRUE, TRUE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (14500, 14000, 'SECURITY_QUALITY_OTHER', '기타(직접입력)', 3, TRUE, TRUE, TRUE, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- =========================================================
-- 기획·전략
-- =========================================================
INSERT IGNORE INTO job_category (
    id, parent_id, category_code, category_name, depth,
    is_active, is_assignable, allows_custom_input,
    sort_order, created_at, updated_at
) VALUES
    (21000, 20000, 'PRODUCT_PLANNING', '프로덕트 기획', 2, TRUE, FALSE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (22000, 20000, 'BUSINESS_STRATEGY', '비즈니스·전략 기획', 2, TRUE, FALSE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (23000, 20000, 'RESEARCH_INVESTMENT', '리서치·투자', 2, TRUE, FALSE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT IGNORE INTO job_category (
    id, parent_id, category_code, category_name, depth,
    is_active, is_assignable, allows_custom_input,
    sort_order, created_at, updated_at
) VALUES
    (21100, 21000, 'SERVICE_PLANNER', '서비스 기획', 3, TRUE, TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (21200, 21000, 'PRODUCT_MANAGER', 'PM', 3, TRUE, TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (21300, 21000, 'PRODUCT_OWNER', 'PO', 3, TRUE, TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (21400, 21000, 'PROJECT_MANAGER', '프로젝트 매니저', 3, TRUE, TRUE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (21500, 21000, 'UX_PLANNER', 'UX 기획', 3, TRUE, TRUE, FALSE, 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (21600, 21000, 'PRODUCT_PLANNING_OTHER', '기타(직접입력)', 3, TRUE, TRUE, TRUE, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (22100, 22000, 'BUSINESS_PLANNER', '사업 기획', 3, TRUE, TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (22200, 22000, 'STRATEGY_PLANNER', '전략 기획', 3, TRUE, TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (22300, 22000, 'NEW_BUSINESS_PLANNER', '신사업 기획', 3, TRUE, TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (22400, 22000, 'OPERATION_PLANNER', '운영 기획', 3, TRUE, TRUE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (22500, 22000, 'BUSINESS_STRATEGY_OTHER', '기타(직접입력)', 3, TRUE, TRUE, TRUE, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (23100, 23000, 'IR', 'IR', 3, TRUE, TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (23200, 23000, 'INVESTMENT_REVIEW', '투자 심사', 3, TRUE, TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (23300, 23000, 'MARKET_RESEARCH', '시장·사업 리서치', 3, TRUE, TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (23400, 23000, 'CONSULTANT', '컨설턴트', 3, TRUE, TRUE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (23500, 23000, 'RESEARCH_INVESTMENT_OTHER', '기타(직접입력)', 3, TRUE, TRUE, TRUE, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- =========================================================
-- 디자인
-- =========================================================
INSERT IGNORE INTO job_category (
    id, parent_id, category_code, category_name, depth,
    is_active, is_assignable, allows_custom_input,
    sort_order, created_at, updated_at
) VALUES
    (31000, 30000, 'UI_UX_PRODUCT_DESIGN', 'UI·UX·프로덕트 디자인', 2, TRUE, FALSE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (32000, 30000, 'VISUAL_BRAND_DESIGN', '비주얼·브랜드 디자인', 2, TRUE, FALSE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (33000, 30000, 'VIDEO_MOTION_DESIGN', '영상·모션 디자인', 2, TRUE, FALSE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (34000, 30000, 'PRODUCT_INDUSTRIAL_DESIGN', '제품·산업 디자인', 2, TRUE, FALSE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT IGNORE INTO job_category (
    id, parent_id, category_code, category_name, depth,
    is_active, is_assignable, allows_custom_input,
    sort_order, created_at, updated_at
) VALUES
    (31100, 31000, 'UI_DESIGNER', 'UI 디자이너', 3, TRUE, TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (31200, 31000, 'UX_DESIGNER', 'UX 디자이너', 3, TRUE, TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (31300, 31000, 'PRODUCT_DESIGNER', '프로덕트 디자이너', 3, TRUE, TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (31400, 31000, 'UX_RESEARCHER', 'UX 리서처', 3, TRUE, TRUE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (31500, 31000, 'UI_UX_PRODUCT_DESIGN_OTHER', '기타(직접입력)', 3, TRUE, TRUE, TRUE, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (32100, 32000, 'GRAPHIC_DESIGNER', '그래픽 디자이너', 3, TRUE, TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (32200, 32000, 'BRAND_DESIGNER', '브랜드 디자이너', 3, TRUE, TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (32300, 32000, 'CONTENT_DESIGNER', '콘텐츠 디자이너', 3, TRUE, TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (32400, 32000, 'ILLUSTRATOR', '일러스트레이터', 3, TRUE, TRUE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (32500, 32000, 'VISUAL_BRAND_DESIGN_OTHER', '기타(직접입력)', 3, TRUE, TRUE, TRUE, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (33100, 33000, 'MOTION_DESIGNER', '모션 디자이너', 3, TRUE, TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (33200, 33000, 'VIDEO_EDITOR', '영상 편집', 3, TRUE, TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (33300, 33000, 'THREE_D_GRAPHICS_DESIGNER', '3D 그래픽', 3, TRUE, TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (33400, 33000, 'VIDEO_MOTION_DESIGN_OTHER', '기타(직접입력)', 3, TRUE, TRUE, TRUE, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (34100, 34000, 'INDUSTRIAL_DESIGNER', '산업 디자이너', 3, TRUE, TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (34200, 34000, 'PACKAGE_DESIGNER', '패키지 디자이너', 3, TRUE, TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (34300, 34000, 'SPACE_EXHIBITION_DESIGNER', '공간·전시 디자이너', 3, TRUE, TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (34400, 34000, 'PRODUCT_INDUSTRIAL_DESIGN_OTHER', '기타(직접입력)', 3, TRUE, TRUE, TRUE, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- =========================================================
-- 마케팅·광고
-- =========================================================
INSERT IGNORE INTO job_category (
    id, parent_id, category_code, category_name, depth,
    is_active, is_assignable, allows_custom_input,
    sort_order, created_at, updated_at
) VALUES
    (41000, 40000, 'DIGITAL_PERFORMANCE_MARKETING', '디지털·퍼포먼스 마케팅', 2, TRUE, FALSE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (42000, 40000, 'BRAND_CONTENT_MARKETING', '브랜드·콘텐츠 마케팅', 2, TRUE, FALSE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (43000, 40000, 'PR_COMMUNICATION', 'PR·커뮤니케이션', 2, TRUE, FALSE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (44000, 40000, 'CRM_GROWTH_MARKETING', 'CRM·그로스 마케팅', 2, TRUE, FALSE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT IGNORE INTO job_category (
    id, parent_id, category_code, category_name, depth,
    is_active, is_assignable, allows_custom_input,
    sort_order, created_at, updated_at
) VALUES
    (41100, 41000, 'PERFORMANCE_MARKETER', '퍼포먼스 마케팅', 3, TRUE, TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (41200, 41000, 'SEO_ASO_MARKETER', 'SEO·ASO', 3, TRUE, TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (41300, 41000, 'APP_MARKETER', '앱 마케팅', 3, TRUE, TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (41400, 41000, 'DIGITAL_PERFORMANCE_MARKETING_OTHER', '기타(직접입력)', 3, TRUE, TRUE, TRUE, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (42100, 42000, 'BRAND_MARKETER', '브랜드 마케팅', 3, TRUE, TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (42200, 42000, 'CONTENT_MARKETER', '콘텐츠 마케팅', 3, TRUE, TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (42300, 42000, 'SNS_MARKETER', 'SNS 마케팅', 3, TRUE, TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (42400, 42000, 'COPYWRITER', '카피라이터', 3, TRUE, TRUE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (42500, 42000, 'BRAND_CONTENT_MARKETING_OTHER', '기타(직접입력)', 3, TRUE, TRUE, TRUE, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (43100, 43000, 'PR_MANAGER', 'PR·홍보', 3, TRUE, TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (43200, 43000, 'CORPORATE_COMMUNICATION_MANAGER', '기업 커뮤니케이션', 3, TRUE, TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (43300, 43000, 'INFLUENCER_MARKETER', '인플루언서 마케팅', 3, TRUE, TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (43400, 43000, 'PR_COMMUNICATION_OTHER', '기타(직접입력)', 3, TRUE, TRUE, TRUE, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (44100, 44000, 'CRM_MARKETER', 'CRM 마케팅', 3, TRUE, TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (44200, 44000, 'GROWTH_MARKETER', '그로스 마케팅', 3, TRUE, TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (44300, 44000, 'MARKETING_AUTOMATION_MANAGER', '마케팅 자동화', 3, TRUE, TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (44400, 44000, 'CRM_GROWTH_MARKETING_OTHER', '기타(직접입력)', 3, TRUE, TRUE, TRUE, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- =========================================================
-- 경영·비즈니스
-- =========================================================
INSERT IGNORE INTO job_category (
    id, parent_id, category_code, category_name, depth,
    is_active, is_assignable, allows_custom_input,
    sort_order, created_at, updated_at
) VALUES
    (51000, 50000, 'HR_ORGANIZATION', '인사·조직', 2, TRUE, FALSE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (52000, 50000, 'FINANCE_ACCOUNTING', '재무·회계', 2, TRUE, FALSE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (53000, 50000, 'LEGAL_COMPLIANCE', '법무·컴플라이언스', 2, TRUE, FALSE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (54000, 50000, 'OPERATIONS_PROCUREMENT', '운영·구매', 2, TRUE, FALSE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT IGNORE INTO job_category (
    id, parent_id, category_code, category_name, depth,
    is_active, is_assignable, allows_custom_input,
    sort_order, created_at, updated_at
) VALUES
    (51100, 51000, 'HR_GENERALIST', 'HR', 3, TRUE, TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (51200, 51000, 'TALENT_ACQUISITION', '채용', 3, TRUE, TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (51300, 51000, 'HRBP', 'HRBP', 3, TRUE, TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (51400, 51000, 'COMPENSATION_BENEFITS_MANAGER', '보상·평가', 3, TRUE, TRUE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (51500, 51000, 'HR_ORGANIZATION_OTHER', '기타(직접입력)', 3, TRUE, TRUE, TRUE, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (52100, 52000, 'ACCOUNTANT', '회계', 3, TRUE, TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (52200, 52000, 'FINANCE_MANAGER', '재무', 3, TRUE, TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (52300, 52000, 'FPNA_MANAGER', 'FP&A', 3, TRUE, TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (52400, 52000, 'TAX_MANAGER', '세무', 3, TRUE, TRUE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (52500, 52000, 'FINANCE_ACCOUNTING_OTHER', '기타(직접입력)', 3, TRUE, TRUE, TRUE, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (53100, 53000, 'LEGAL_COUNSEL', '법무', 3, TRUE, TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (53200, 53000, 'COMPLIANCE_MANAGER', '컴플라이언스', 3, TRUE, TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (53300, 53000, 'CONTRACT_MANAGER', '계약 관리', 3, TRUE, TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (53400, 53000, 'LEGAL_COMPLIANCE_OTHER', '기타(직접입력)', 3, TRUE, TRUE, TRUE, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (54100, 54000, 'BUSINESS_OPERATIONS_MANAGER', '비즈니스 운영', 3, TRUE, TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (54200, 54000, 'PROCUREMENT_MANAGER', '구매·조달', 3, TRUE, TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (54300, 54000, 'SUPPLY_CHAIN_MANAGER', 'SCM', 3, TRUE, TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (54400, 54000, 'OFFICE_ADMINISTRATOR', '사무·행정', 3, TRUE, TRUE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (54500, 54000, 'OPERATIONS_PROCUREMENT_OTHER', '기타(직접입력)', 3, TRUE, TRUE, TRUE, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- =========================================================
-- 영업·서비스
-- =========================================================
INSERT IGNORE INTO job_category (
    id, parent_id, category_code, category_name, depth,
    is_active, is_assignable, allows_custom_input,
    sort_order, created_at, updated_at
) VALUES
    (61000, 60000, 'B2B_SALES', 'B2B 영업', 2, TRUE, FALSE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (62000, 60000, 'B2C_RETAIL_SALES', 'B2C·리테일 영업', 2, TRUE, FALSE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (63000, 60000, 'CUSTOMER_SUCCESS_SUPPORT', '고객성공·지원', 2, TRUE, FALSE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (64000, 60000, 'PARTNERSHIP_BD', '파트너십·BD', 2, TRUE, FALSE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT IGNORE INTO job_category (
    id, parent_id, category_code, category_name, depth,
    is_active, is_assignable, allows_custom_input,
    sort_order, created_at, updated_at
) VALUES
    (61100, 61000, 'ENTERPRISE_SALES', '기업 영업', 3, TRUE, TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (61200, 61000, 'SOLUTION_SALES', '솔루션 영업', 3, TRUE, TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (61300, 61000, 'TECHNICAL_SALES', '기술 영업', 3, TRUE, TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (61400, 61000, 'B2B_SALES_OTHER', '기타(직접입력)', 3, TRUE, TRUE, TRUE, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (62100, 62000, 'RETAIL_SALES', '리테일 영업', 3, TRUE, TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (62200, 62000, 'FIELD_SALES', '필드 세일즈', 3, TRUE, TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (62300, 62000, 'INSIDE_SALES', '인사이드 세일즈', 3, TRUE, TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (62400, 62000, 'B2C_RETAIL_SALES_OTHER', '기타(직접입력)', 3, TRUE, TRUE, TRUE, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (63100, 63000, 'CUSTOMER_SERVICE', '고객 상담·CS', 3, TRUE, TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (63200, 63000, 'CUSTOMER_SUCCESS_MANAGER', 'CSM', 3, TRUE, TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (63300, 63000, 'CX_MANAGER', 'CX 매니저', 3, TRUE, TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (63400, 63000, 'TECHNICAL_SUPPORT_ENGINEER', '기술 지원', 3, TRUE, TRUE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (63500, 63000, 'CUSTOMER_SUCCESS_SUPPORT_OTHER', '기타(직접입력)', 3, TRUE, TRUE, TRUE, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (64100, 64000, 'PARTNERSHIP_MANAGER', '파트너십', 3, TRUE, TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (64200, 64000, 'BUSINESS_DEVELOPMENT_MANAGER', '사업 개발', 3, TRUE, TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (64300, 64000, 'ALLIANCE_MANAGER', '전략 제휴', 3, TRUE, TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (64400, 64000, 'PARTNERSHIP_BD_OTHER', '기타(직접입력)', 3, TRUE, TRUE, TRUE, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- =========================================================
-- 미디어·콘텐츠
-- =========================================================
INSERT IGNORE INTO job_category (
    id, parent_id, category_code, category_name, depth,
    is_active, is_assignable, allows_custom_input,
    sort_order, created_at, updated_at
) VALUES
    (71000, 70000, 'EDITORIAL_WRITING', '에디토리얼·글쓰기', 2, TRUE, FALSE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (72000, 70000, 'VIDEO_PRODUCTION', '영상 제작', 2, TRUE, FALSE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (73000, 70000, 'CREATOR_SOCIAL', '크리에이터·소셜', 2, TRUE, FALSE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (74000, 70000, 'GAME_CONTENT', '게임 콘텐츠', 2, TRUE, FALSE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT IGNORE INTO job_category (
    id, parent_id, category_code, category_name, depth,
    is_active, is_assignable, allows_custom_input,
    sort_order, created_at, updated_at
) VALUES
    (71100, 71000, 'REPORTER', '기자', 3, TRUE, TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (71200, 71000, 'EDITOR', '에디터', 3, TRUE, TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (71300, 71000, 'WRITER', '작가', 3, TRUE, TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (71400, 71000, 'SCRIPT_WRITER', '방송·영상 작가', 3, TRUE, TRUE, FALSE, 40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (71500, 71000, 'EDITORIAL_WRITING_OTHER', '기타(직접입력)', 3, TRUE, TRUE, TRUE, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (72100, 72000, 'PRODUCER_PD', 'PD', 3, TRUE, TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (72200, 72000, 'CAMERA_OPERATOR', '촬영', 3, TRUE, TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (72300, 72000, 'VIDEO_EDITOR_CONTENT', '영상 편집', 3, TRUE, TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (72400, 72000, 'VIDEO_PRODUCTION_OTHER', '기타(직접입력)', 3, TRUE, TRUE, TRUE, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (73100, 73000, 'CREATOR', '크리에이터', 3, TRUE, TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (73200, 73000, 'STREAMER', '스트리머', 3, TRUE, TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (73300, 73000, 'SOCIAL_MEDIA_MANAGER', '소셜미디어 운영', 3, TRUE, TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (73400, 73000, 'CREATOR_SOCIAL_OTHER', '기타(직접입력)', 3, TRUE, TRUE, TRUE, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (74100, 74000, 'GAME_PLANNER', '게임 기획', 3, TRUE, TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (74200, 74000, 'GAME_ARTIST', '게임 아트', 3, TRUE, TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (74300, 74000, 'GAME_OPERATIONS_MANAGER', '게임 운영', 3, TRUE, TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (74400, 74000, 'GAME_CONTENT_OTHER', '기타(직접입력)', 3, TRUE, TRUE, TRUE, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- =========================================================
-- 교육
-- =========================================================
INSERT IGNORE INTO job_category (
    id, parent_id, category_code, category_name, depth,
    is_active, is_assignable, allows_custom_input,
    sort_order, created_at, updated_at
) VALUES
    (81000, 80000, 'TEACHING_TUTORING', '강의·튜터링', 2, TRUE, FALSE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (82000, 80000, 'LEARNING_DESIGN_OPERATIONS', '교육 기획·운영', 2, TRUE, FALSE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (83000, 80000, 'CORPORATE_LD_HRD', '기업 교육·HRD', 2, TRUE, FALSE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT IGNORE INTO job_category (
    id, parent_id, category_code, category_name, depth,
    is_active, is_assignable, allows_custom_input,
    sort_order, created_at, updated_at
) VALUES
    (81100, 81000, 'INSTRUCTOR', '강사', 3, TRUE, TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (81200, 81000, 'TUTOR', '튜터', 3, TRUE, TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (81300, 81000, 'CODING_INSTRUCTOR', '코딩 강사', 3, TRUE, TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (81400, 81000, 'TEACHING_TUTORING_OTHER', '기타(직접입력)', 3, TRUE, TRUE, TRUE, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (82100, 82000, 'CURRICULUM_PLANNER', '커리큘럼 기획', 3, TRUE, TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (82200, 82000, 'EDUCATION_OPERATIONS_MANAGER', '교육 운영', 3, TRUE, TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (82300, 82000, 'INSTRUCTIONAL_DESIGNER', '교수 설계', 3, TRUE, TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (82400, 82000, 'LEARNING_DESIGN_OPERATIONS_OTHER', '기타(직접입력)', 3, TRUE, TRUE, TRUE, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (83100, 83000, 'HRD_MANAGER', 'HRD', 3, TRUE, TRUE, FALSE, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (83200, 83000, 'CORPORATE_TRAINER', '사내 강사', 3, TRUE, TRUE, FALSE, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (83300, 83000, 'ORGANIZATION_DEVELOPMENT_FACILITATOR', '조직 개발', 3, TRUE, TRUE, FALSE, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (83400, 83000, 'CORPORATE_LD_HRD_OTHER', '기타(직접입력)', 3, TRUE, TRUE, TRUE, 99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
